name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'whenissunset'
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
        env:
          HD_PORT: 8080